In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
file_path = r"C:\Users\FUJITSU\Downloads\olx_car_data_csv.csv"
cars_data = pd.read_csv(file_path)

In [9]:
cars_data.head()

,Brand,Condition,Fuel,KMs Driven,Model,Price,Registered City,Transaction Type,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000.0,Karachi,Cash,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000.0,Karachi,Cash,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000.0,Karachi,Cash,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000.0,Karachi,Cash,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000.0,Karachi,Cash,2013.0

In [10]:
cars_data.shape

(10577, 9)

In [11]:
cars_data.isnull().sum()

Brand                793
Condition            792
Fuel                 931
KMs Driven           853
Model                934
Price                  1
Registered City     1826
Transaction Type     931
Year                 852
dtype: int64

In [12]:
cars_data.dropna(inplace=True)

In [13]:
cars_data.shape

(8748, 9)

In [14]:
cars_data.duplicated().sum()

np.int64(340)

In [15]:
cars_data.duplicated().sum()

np.int64(340)

In [16]:
cars_data.drop_duplicates(inplace=True)

In [17]:
cars_data.shape

(8408, 9)

In [18]:
cars_data

,Brand,Condition,Fuel,KMs Driven,Model,Price,Registered City,Transaction Type,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000.0,Karachi,Cash,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000.0,Karachi,Cash,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000.0,Karachi,Cash,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000.0,Karachi,Cash,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000.0,Karachi,Cash,2013.0
...,...,...,...,...,...,...,...,...,...
10572,Suzuki,Used,Petrol,10000.0,Cultus VXR,495000.0,Karachi,Cash,2004.0
10573,Suzuki,Used,Petrol,30000.0,Margalla,385000.0,Karachi,Cash,1996.0
10574,Suzuki,Used,CNG,90000.0,Cultus VXR,660000.0,Karachi,Cash,2010.0
10575,Suzuki,Used,Petrol,25000.0,Cultus VXL,750000.0,Karachi,Cash,2012.0
10576,Honda,Used,CNG,123456.0,Civic EXi,230000.0,Karachi,Cash,1989.0

In [19]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8408 entries, 0 to 10576
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             8408 non-null   object
 1   Condition         8408 non-null   object
 2   Fuel              8408 non-null   object
 3   KMs Driven        8408 non-null   float64
 4   Model             8408 non-null   object
 5   Price             8408 non-null   float64
 6   Registered City   8408 non-null   object
 7   Transaction Type  8408 non-null   object
 8   Year              8408 non-null   float64
dtypes: float64(3), object(6)
memory usage: 656.9+ KB

In [20]:
for col in cars_data.columns:
    print('Unique values of ' + col)
    print(cars_data[col].unique())
    print("======================")

Unique values of Brand
['Toyota' 'Suzuki' 'Honda' 'Daihatsu' 'Mitsubishi' 'KIA' 'Other Brands'
 'Nissan' 'BMW' 'Mazda' 'Chevrolet' 'Daewoo' 'Hyundai' 'FAW' 'Mercedes'
 'Classic & Antiques' 'Lexus' 'Audi' 'Range Rover' 'Changan' 'Porsche']
======================
Unique values of Condition
['Used' 'New']
======================
Unique values of Fuel
['Diesel' 'Petrol' 'CNG' 'Hybrid' 'LPG']
======================
Unique values of KMs Driven
[1.00000e+00 1.00000e+05 1.23450e+04 ... 1.00008e+05 5.63000e+04
 3.68525e+05]
======================
Unique values of Model
['Prado' 'Bolan' 'Alto' 'Corolla XLI' 'Corrolla Altis' 'Cultus VXL'
 'Civic VTi' 'Khyber' 'Liana' 'Passo' 'Civic Prosmetic' 'Civic EXi'
 'Charade' 'Pajero Mini' 'Margalla' 'City IVTEC' 'Classic' 'Other'
 'Corolla GLI' 'Cultus VXR' 'Dayz Highway Star' 'Mehran VX' 'Vitz'
 'Mehran VXR' 'Carry' 'Cultus VX' 'Baleno' 'Mira'
 'Civic VTi Oriel Prosmatec' 'Cuore' 'Corolla 2.0 D' 'Corolla XE' 'Surf'
 'FX' 'City IDSI' 'Premio' 'Sprinter' '3 Series' 'Hilux' 'Lancer' 'Swift'
 'Estima' 'Vamos' 'Starlet' 'Prius' 'Joy' '323' 'Racer' 'Sunny' 'Accord'
 'Zest' 'AD Van' 'APV' 'March' 'Pride' 'Sportage' 'Terios Kid' 'Santro'
 'Fit' 'V2' 'City Aspire' 'Civic VTi Oriel' 'BR-V' 'Kei' 'Probox' 'Hijet'
 '86' 'Yaris' 'Aygo' 'Rush' 'Dayz' 'Fortuner' 'Every' 'Camry' 'Aqua'
 'Corolla Assista' 'Sera' 'Acty' 'Moco' 'Wagon R' 'Smart' 'Demio' 'Corona'
 'Every Wagon' 'Civic Hybrid' 'Duet' 'Vezel' 'Corolla Axio' 'City Vario'
 'Corolla Fielder' 'Palette Sw' 'Platz' 'Lancer Evolution' 'Move'
 'Gx Series' '5 Series' '240 Gd' 'Mira Cocoa' 'Wingroad' 'Belta'
 'Atrai Wagon' 'Minicab Bravo' 'Allion' 'Blue Bird' 'Exclusive' 'N Wgn'
 'CT200h' 'Spectra' 'Beat' 'Mark II' 'Airwave' 'Supra' 'Ek Wagon'
 'EK Custom' 'Lite Ace' '120 Y' 'Harrier' 'Pixis Epoch' '626' 'Galant'
 'Sonica' 'Carol Eco' 'Accent' 'IST' 'Land Cruiser' 'Palette' 'Juke'
 'Potohar' 'CR-V' 'Clipper' 'Sirius' 'Roox' '350Z' 'Pajero' 'Vitara'
 'Alto Lapin' 'Wagon R Stingray' 'Prius Alpha' 'Minica' 'Cast' 'Carol'
 'Hustler' 'S Class' 'Boon' 'Jimny' 'Fj Cruiser' 'X-PV' 'Esse' 'Mirage'
 'RX8' 'Carisma' 'iQ' 'Ek Sport' 'CLK Class' 'Note' 'Stream' 'Carrier'
 'Town Ace' 'I' 'N Box' 'Excel' 'B2200' 'Tundra' 'Scrum' 'Celica' 'Van'
 'C Class' 'Pickup' 'Kizashi' 'Freed' 'RX Series' 'Life' 'Otti' 'Spacia'
 'Cervo' 'X5 Series' '200 D' 'Patrol' 'Acura' 'Crown' 'Copen'
 'Scrum Wagon' 'Charmant' 'Mark X' 'Spike' 'Vogue' 'Axela' '929' 'Ravi'
 'Noah' 'Jade Hybrid' 'Tanto' 'X Trail' 'EK Space Custom' 'Cielo'
 'I Mivec' 'N One' 'i8' 'S660' 'Tiida' 'CR-Z' 'Verossa' 'Flair Wagon'
 'Grace Hybrid' 'E Class' 'Wish' 'L300' 'Auris' 'Cayenne' 'Silverado'
 'Insight' 'Thats' 'C-HR' 'Familia Van' 'Jimny Sierra' 'D Series' 'Escudo'
 'Vanette' 'Rvr' 'LX Series' '250 D' 'Cami' 'Bluebird Sylphy' 'Pino'
 'Ignis' 'A4' 'Wake' 'Spark' 'Sirion' 'Q7' 'Zest Spark' 'Cruze' 'Avanza'
 'Flair' 'ISIS' 'Cross Road' '7 Series' 'Matiz' 'Pulsar' 'Ciaz' 'A6'
 'Sonata' '6 Series' 'Cressida' 'Solio' 'Alphard Hybrid' 'Azwagon' 'Rav4'
 'Toyo Ace']
======================
Unique values of Price
[ 2100000.   380000.   340000.   535000.  1430000.  1620000.   450000.
  2900000.   490000.   480000.   230000.   770000.   160000.   425000.
   180000.   520000.   400000.  1400000.   175000.   120000.   590000.
   685000.   465000.  1190000.   850000.   370000.  1175000.  1675000.
   195000.   165000.   420000.   150000.   130000.   415000.   185000.
  1040000.   360000.  1150000.   265000.   435000.  1220000.   780000.
   250000.   875000.  1260000.   840000.   350000.  1050000.   730000.
  1070000.   410000.   155000.   320000.  1080000.   290000.   570000.
  4150000.    90000.  1740000.   916000.   110000.   765000.  1890000.
   790000.   785000.   270000.   550000.   825000.  3850000.  1250000.
   135000.  4500000.   430000.  2880000.   975000.   440000.   305000.
  1140000.   680000.   335000.  3350000.   405000.   865000.  1090000.
   300000.   750000.   820000.   373000.  2500000.  5350000.   200000.
  1160000.  9000000.    55000.  1110000.  2830000.   740000.   560000.
   690000.  1095000.   145000.  1710000.   900000.  2175000.   105000.
   485000.  1350000.  1100000.   260000.   210000.   170000.  1320000.
  1000000.   220000.   950000.   930000.  1275000.   760000.   980000.
   855000.   600000.    68000.   500000.   700000.   580000.   225000.
  1625000.   118000.   168000.   650000.    95000.   585000.  1525000.
  1730000.  2000000.   545000.   830000.   190000.   293000.   510000.
   310000.   365000.   540000.   330000.  1450000.   995000.   315000.
  1750000.  1079000.   530000.   245000.   910000.   280000.  1975000.
   860000.  1600000.   725000.   240000.   140000.   965000.  2325000.
  1120000.   960000.    60000.   795000.  1135000.   800000.   695000.
  1650000.  1550000.  1165000.  7550000.   215000.  1060000.  1200000.
  1125000.  1810000.  1900000.  1225000.  1375000.  2835000.   575000.
  1660000.   660000.   775000.   810000.   920000.   625000.  1850000.
   565000.  1170000.  1315000.   235000.   534999.   285000.  1865000.
  1425000.   880000.  1830000.  1490000.  1575000.   635000.  1025000.
   812000.   199000.   845000.  1185000.  1560000.   255000.   665000.
  1800000.  1396000.  1215000.   985000.   555000.   100000.   696000.
   935000.  1195000.   885000.   460000.   745000.   945000.   375000.
  2750000.  3200000.   835000.   413000.   675000.  1469000.  1775000.
   525000.  1300000.   505000.   470000.  2250000.  1370000.   355000.
  1285000.  1500000.   475000.   670000.  1995000.  1390000.   818000.
  1820000.  2650000.   710000.    85000.  2725000.  1020000.  1465000.
  1210000.  4600000.   395000.  2050000.   876000.   538000.  5000000.
  3090000.  2310000.   610000.  4000000.  1760000.  1340000.  1280000.
   848000.  1149000.   990000.   125000.   295000.  1325000.   284999.
   541000.   615000.  2350000.   620000.   521000.   669000.    80000.
   205000.  1035000.  1265000.  1075000.  1720000.   515000.   572500.
   385000.    75000.  2075000.  1178000.  1745000.   390000.  1875000.
  2700000.  1630000.  2800000.  2150000.   970000.  1055000.  2400000.
  1065000.   735000.   548000.   925000.   819000.   915000.   955000.
   495000.   595000.   630000.   499999.  1915000.  1965000.   870000.
   655000.   815000.  1245000.  2225000.  2385000.  1475000.  3900000.
  1725000.  1950000.  2290000.   890000.  1230000.  1275786.  2200000.
  1010000.  1835000.  1655000.  3050000.   275000.  3000000.   238000.
   720000.   361099.  5450000.   115000.    50000.  1585000.  3750000.
   137500.  1695000.  1030000.    70000.  3700000.   189000.  1149999.
  1255000.  1314000.   213500.  1180000.   382000.  1299987.  1580000.
  3295000.  2230000.  1700000.  4400000.   445000.   700001.    65000.
   645000.   399000.   347000.  2140000.   112000. 27000000.  1145000.
  9100000.   640000.  3925000.   755000.   455000.  2690000.  2300000.
  6420000.  2600000.  1520000.  1360000.   943000.   715000.  1590000.
   444000.  1005000.  1395000.  1920000.  1785000.   159000.   699000.
  2665000.  6000000.   789000. 10000000.   325000.   324999.   258000.
   133000.  2180000.   605000.  1860000.  2090000.  1290000.   805000.
   268000.  1410000.   429000.  2285000.  2445000.   895000.  1270000.
  4100000.  1825000.  4975000.  2270000.  1115000.  2780000.   598000.
  2450000.  1295000.  3125000.   276000.  1385000.  1910000.  1790000.
  1940000.  2335000.  1130000.  2875000.  1085000.  2865000.  2060000.
  1015000.   402000.  1705000.   148000.  1670000.  2380000.  5800000.
  1440000.  1460000.  1545000.  2080000.   741000.  1240000.   272000.
   589000.   389999.  1985000.   359000.  2425000.  1925000.  1204000.
  1715000.  1665000.    99000.   492000.   222000.  6800000.   299000.
  2125000.  7500000.   642000.  2085000.  1345000.  1470000.   452000.
  1599000.  1680000.  2275000.  2979000.  1885000.  1770000.  1420000.
  2020000.  1310000.  1780000.  2565000.  2287650.  2195000.  2228650.
   999999.   567000.   998000.  1945000.  1990000.  1635000.  6500000.
   425200.   345000.  2340000.  2480000.   749000.  1570000.  1815000.
  2550000.  1565000.   331000.   187000.  6350000.  1870000.  2950000.
   940000.  4650000.  1235000.  6450000.  1930000.  1199000.  5100000.
  3095000.  3800000.  2015000.   489000.   412000.  1685000.   231000.
   858000. 12500000.  1330000.  6400000.  2925000.    62000.   993000.
   391000.   869000.  1840000.   299999.  2025000.  1335000.  2850000.
  1595000.    85500.  1540000.  8650000.   338000.   379000.  3070000.
  3170000.   718000.   949000.  2745000.  1994000.   398000.   989500.
  3225000.  4550000.  2490000.   348000.  3500000.  4800000.  2320000.
   497000.  1530000.    98000.  1099999.   799000.   323000.  1380000.
   705000.   899000.   243000.   269000.  2315000.  3150000.  2375000.
  1155000.  1615000.  1045000.    81000.  2675000.  2035000.  1480000.
   122000.   386000.   899999.  7650000.  2625000.   132000.  2065000.
  1399999.  2765000.   232000.   522000.  3380000.   389000.   834000.
   599000.  2129000.   116500.  3600000.   119000.  4900000.    88000.
  1795000.  3950000.   103000.   360009.  1099000.   679000.  9500000.
   288000.  5700000.   163000.  1855000.  3060000.  5500000.  3290000.
   397000.   418000.   588000. 17000000.   954955.  9800000.   324000.
   839000.  3135000.  2825000.   248000.  2530000.  2323000.  3175000.
  4250000.  1415000.  9200000.  1699000.  2975000.  3300000.  1535000.
  4850000.   127500.  1789999.  1435000.    74000.  3400000.  4300000.
   156000.  2980000.   149500.  8400000.  3040000.   298000.  1118000.
   597000.  6300000.   371000.  5400000.   517000.  2190000.  2799000.
   158000.  4350000.  1515000.  2210000.   162000.  1485000.  1234560.
  2030000.  2390000.   173000.   511000. 15000000.   236000.   853000.
  4980000.  1999000. 13500000.  7300000.   796000.  1234000.  1690000.
   107000.  2178000.   487000.   799999.  1043000.]
======================
Unique values of Registered City
['Karachi' 'Hyderabad' 'Bagh' 'Sukkar' 'Bahawalnagar' 'Lahore' 'Askoley'
 'Khanpur' 'Quetta' 'Karak' 'Islamabad' 'Sialkot' 'Pakpattan' 'Lasbela'
 'Sukkur' 'Rawalpindi' 'Bahawalpur' 'Ali Masjid' 'Multan' 'Khaplu' 'Tank'
 'Badin' 'Rahimyar Khan' 'Chilas' 'Kasur' 'Khushab' 'Vehari' 'Chitral'
 'Khanewal' 'Attock' 'Larkana' 'Bela' 'Khairpur']
======================
Unique values of Transaction Type
['Cash' 'Installment/Leasing']
======================
Unique values of Year
[1997. 2006. 1998. 2010. 2013. 2012. 2017. 2009. 1994. 1984. 2005. 1988.
 1995. 1990. 2014. 1989. 2001. 2000. 2007. 2002. 2015. 1999. 1991. 1982.
 2004. 2003. 2011. 1987. 1993. 2016. 1986. 2008. 2018. 1981. 1978. 1996.
 1985. 1992. 1980. 1983. 1973. 1964. 1969. 1952. 1979. 1974. 1976. 1962.
 1967. 1970. 1972. 1960. 1951. 1963. 1977. 1971. 1975. 1925. 1968.]
======================

In [21]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip()

In [ ]:
def clean_data(value):
 #   value = value.split(' ')[0]
  #  value = value.strip()
   # if value == '':
    #    value = 0
    #return float(value)

In [22]:
get_brand_name('Toyota')

'Toyota'

In [23]:
cars_data['Brand'] = cars_data['Brand'].apply(get_brand_name)

In [24]:
cars_data['Brand'].unique()

array(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',
       'Other', 'Nissan', 'BMW', 'Mazda', 'Chevrolet', 'Daewoo',
       'Hyundai', 'FAW', 'Mercedes', 'Classic', 'Lexus', 'Audi', 'Range',
       'Changan', 'Porsche'], dtype=object)

In [25]:
for col in cars_data.columns:
    print('Unique values of ' + col)
    print(cars_data[col].unique())
    print("======================")

Unique values of Brand
['Toyota' 'Suzuki' 'Honda' 'Daihatsu' 'Mitsubishi' 'KIA' 'Other' 'Nissan'
 'BMW' 'Mazda' 'Chevrolet' 'Daewoo' 'Hyundai' 'FAW' 'Mercedes' 'Classic'
 'Lexus' 'Audi' 'Range' 'Changan' 'Porsche']
======================
Unique values of Condition
['Used' 'New']
======================
Unique values of Fuel
['Diesel' 'Petrol' 'CNG' 'Hybrid' 'LPG']
======================
Unique values of KMs Driven
[1.00000e+00 1.00000e+05 1.23450e+04 ... 1.00008e+05 5.63000e+04
 3.68525e+05]
======================
Unique values of Model
['Prado' 'Bolan' 'Alto' 'Corolla XLI' 'Corrolla Altis' 'Cultus VXL'
 'Civic VTi' 'Khyber' 'Liana' 'Passo' 'Civic Prosmetic' 'Civic EXi'
 'Charade' 'Pajero Mini' 'Margalla' 'City IVTEC' 'Classic' 'Other'
 'Corolla GLI' 'Cultus VXR' 'Dayz Highway Star' 'Mehran VX' 'Vitz'
 'Mehran VXR' 'Carry' 'Cultus VX' 'Baleno' 'Mira'
 'Civic VTi Oriel Prosmatec' 'Cuore' 'Corolla 2.0 D' 'Corolla XE' 'Surf'
 'FX' 'City IDSI' 'Premio' 'Sprinter' '3 Series' 'Hilux' 'Lancer' 'Swift'
 'Estima' 'Vamos' 'Starlet' 'Prius' 'Joy' '323' 'Racer' 'Sunny' 'Accord'
 'Zest' 'AD Van' 'APV' 'March' 'Pride' 'Sportage' 'Terios Kid' 'Santro'
 'Fit' 'V2' 'City Aspire' 'Civic VTi Oriel' 'BR-V' 'Kei' 'Probox' 'Hijet'
 '86' 'Yaris' 'Aygo' 'Rush' 'Dayz' 'Fortuner' 'Every' 'Camry' 'Aqua'
 'Corolla Assista' 'Sera' 'Acty' 'Moco' 'Wagon R' 'Smart' 'Demio' 'Corona'
 'Every Wagon' 'Civic Hybrid' 'Duet' 'Vezel' 'Corolla Axio' 'City Vario'
 'Corolla Fielder' 'Palette Sw' 'Platz' 'Lancer Evolution' 'Move'
 'Gx Series' '5 Series' '240 Gd' 'Mira Cocoa' 'Wingroad' 'Belta'
 'Atrai Wagon' 'Minicab Bravo' 'Allion' 'Blue Bird' 'Exclusive' 'N Wgn'
 'CT200h' 'Spectra' 'Beat' 'Mark II' 'Airwave' 'Supra' 'Ek Wagon'
 'EK Custom' 'Lite Ace' '120 Y' 'Harrier' 'Pixis Epoch' '626' 'Galant'
 'Sonica' 'Carol Eco' 'Accent' 'IST' 'Land Cruiser' 'Palette' 'Juke'
 'Potohar' 'CR-V' 'Clipper' 'Sirius' 'Roox' '350Z' 'Pajero' 'Vitara'
 'Alto Lapin' 'Wagon R Stingray' 'Prius Alpha' 'Minica' 'Cast' 'Carol'
 'Hustler' 'S Class' 'Boon' 'Jimny' 'Fj Cruiser' 'X-PV' 'Esse' 'Mirage'
 'RX8' 'Carisma' 'iQ' 'Ek Sport' 'CLK Class' 'Note' 'Stream' 'Carrier'
 'Town Ace' 'I' 'N Box' 'Excel' 'B2200' 'Tundra' 'Scrum' 'Celica' 'Van'
 'C Class' 'Pickup' 'Kizashi' 'Freed' 'RX Series' 'Life' 'Otti' 'Spacia'
 'Cervo' 'X5 Series' '200 D' 'Patrol' 'Acura' 'Crown' 'Copen'
 'Scrum Wagon' 'Charmant' 'Mark X' 'Spike' 'Vogue' 'Axela' '929' 'Ravi'
 'Noah' 'Jade Hybrid' 'Tanto' 'X Trail' 'EK Space Custom' 'Cielo'
 'I Mivec' 'N One' 'i8' 'S660' 'Tiida' 'CR-Z' 'Verossa' 'Flair Wagon'
 'Grace Hybrid' 'E Class' 'Wish' 'L300' 'Auris' 'Cayenne' 'Silverado'
 'Insight' 'Thats' 'C-HR' 'Familia Van' 'Jimny Sierra' 'D Series' 'Escudo'
 'Vanette' 'Rvr' 'LX Series' '250 D' 'Cami' 'Bluebird Sylphy' 'Pino'
 'Ignis' 'A4' 'Wake' 'Spark' 'Sirion' 'Q7' 'Zest Spark' 'Cruze' 'Avanza'
 'Flair' 'ISIS' 'Cross Road' '7 Series' 'Matiz' 'Pulsar' 'Ciaz' 'A6'
 'Sonata' '6 Series' 'Cressida' 'Solio' 'Alphard Hybrid' 'Azwagon' 'Rav4'
 'Toyo Ace']
======================
Unique values of Price
[ 2100000.   380000.   340000.   535000.  1430000.  1620000.   450000.
  2900000.   490000.   480000.   230000.   770000.   160000.   425000.
   180000.   520000.   400000.  1400000.   175000.   120000.   590000.
   685000.   465000.  1190000.   850000.   370000.  1175000.  1675000.
   195000.   165000.   420000.   150000.   130000.   415000.   185000.
  1040000.   360000.  1150000.   265000.   435000.  1220000.   780000.
   250000.   875000.  1260000.   840000.   350000.  1050000.   730000.
  1070000.   410000.   155000.   320000.  1080000.   290000.   570000.
  4150000.    90000.  1740000.   916000.   110000.   765000.  1890000.
   790000.   785000.   270000.   550000.   825000.  3850000.  1250000.
   135000.  4500000.   430000.  2880000.   975000.   440000.   305000.
  1140000.   680000.   335000.  3350000.   405000.   865000.  1090000.
   300000.   750000.   820000.   373000.  2500000.  5350000.   200000.
  1160000.  9000000.    55000.  1110000.  2830000.   740000.   560000.
   690000.  1095000.   145000.  1710000.   900000.  2175000.   105000.
   485000.  1350000.  1100000.   260000.   210000.   170000.  1320000.
  1000000.   220000.   950000.   930000.  1275000.   760000.   980000.
   855000.   600000.    68000.   500000.   700000.   580000.   225000.
  1625000.   118000.   168000.   650000.    95000.   585000.  1525000.
  1730000.  2000000.   545000.   830000.   190000.   293000.   510000.
   310000.   365000.   540000.   330000.  1450000.   995000.   315000.
  1750000.  1079000.   530000.   245000.   910000.   280000.  1975000.
   860000.  1600000.   725000.   240000.   140000.   965000.  2325000.
  1120000.   960000.    60000.   795000.  1135000.   800000.   695000.
  1650000.  1550000.  1165000.  7550000.   215000.  1060000.  1200000.
  1125000.  1810000.  1900000.  1225000.  1375000.  2835000.   575000.
  1660000.   660000.   775000.   810000.   920000.   625000.  1850000.
   565000.  1170000.  1315000.   235000.   534999.   285000.  1865000.
  1425000.   880000.  1830000.  1490000.  1575000.   635000.  1025000.
   812000.   199000.   845000.  1185000.  1560000.   255000.   665000.
  1800000.  1396000.  1215000.   985000.   555000.   100000.   696000.
   935000.  1195000.   885000.   460000.   745000.   945000.   375000.
  2750000.  3200000.   835000.   413000.   675000.  1469000.  1775000.
   525000.  1300000.   505000.   470000.  2250000.  1370000.   355000.
  1285000.  1500000.   475000.   670000.  1995000.  1390000.   818000.
  1820000.  2650000.   710000.    85000.  2725000.  1020000.  1465000.
  1210000.  4600000.   395000.  2050000.   876000.   538000.  5000000.
  3090000.  2310000.   610000.  4000000.  1760000.  1340000.  1280000.
   848000.  1149000.   990000.   125000.   295000.  1325000.   284999.
   541000.   615000.  2350000.   620000.   521000.   669000.    80000.
   205000.  1035000.  1265000.  1075000.  1720000.   515000.   572500.
   385000.    75000.  2075000.  1178000.  1745000.   390000.  1875000.
  2700000.  1630000.  2800000.  2150000.   970000.  1055000.  2400000.
  1065000.   735000.   548000.   925000.   819000.   915000.   955000.
   495000.   595000.   630000.   499999.  1915000.  1965000.   870000.
   655000.   815000.  1245000.  2225000.  2385000.  1475000.  3900000.
  1725000.  1950000.  2290000.   890000.  1230000.  1275786.  2200000.
  1010000.  1835000.  1655000.  3050000.   275000.  3000000.   238000.
   720000.   361099.  5450000.   115000.    50000.  1585000.  3750000.
   137500.  1695000.  1030000.    70000.  3700000.   189000.  1149999.
  1255000.  1314000.   213500.  1180000.   382000.  1299987.  1580000.
  3295000.  2230000.  1700000.  4400000.   445000.   700001.    65000.
   645000.   399000.   347000.  2140000.   112000. 27000000.  1145000.
  9100000.   640000.  3925000.   755000.   455000.  2690000.  2300000.
  6420000.  2600000.  1520000.  1360000.   943000.   715000.  1590000.
   444000.  1005000.  1395000.  1920000.  1785000.   159000.   699000.
  2665000.  6000000.   789000. 10000000.   325000.   324999.   258000.
   133000.  2180000.   605000.  1860000.  2090000.  1290000.   805000.
   268000.  1410000.   429000.  2285000.  2445000.   895000.  1270000.
  4100000.  1825000.  4975000.  2270000.  1115000.  2780000.   598000.
  2450000.  1295000.  3125000.   276000.  1385000.  1910000.  1790000.
  1940000.  2335000.  1130000.  2875000.  1085000.  2865000.  2060000.
  1015000.   402000.  1705000.   148000.  1670000.  2380000.  5800000.
  1440000.  1460000.  1545000.  2080000.   741000.  1240000.   272000.
   589000.   389999.  1985000.   359000.  2425000.  1925000.  1204000.
  1715000.  1665000.    99000.   492000.   222000.  6800000.   299000.
  2125000.  7500000.   642000.  2085000.  1345000.  1470000.   452000.
  1599000.  1680000.  2275000.  2979000.  1885000.  1770000.  1420000.
  2020000.  1310000.  1780000.  2565000.  2287650.  2195000.  2228650.
   999999.   567000.   998000.  1945000.  1990000.  1635000.  6500000.
   425200.   345000.  2340000.  2480000.   749000.  1570000.  1815000.
  2550000.  1565000.   331000.   187000.  6350000.  1870000.  2950000.
   940000.  4650000.  1235000.  6450000.  1930000.  1199000.  5100000.
  3095000.  3800000.  2015000.   489000.   412000.  1685000.   231000.
   858000. 12500000.  1330000.  6400000.  2925000.    62000.   993000.
   391000.   869000.  1840000.   299999.  2025000.  1335000.  2850000.
  1595000.    85500.  1540000.  8650000.   338000.   379000.  3070000.
  3170000.   718000.   949000.  2745000.  1994000.   398000.   989500.
  3225000.  4550000.  2490000.   348000.  3500000.  4800000.  2320000.
   497000.  1530000.    98000.  1099999.   799000.   323000.  1380000.
   705000.   899000.   243000.   269000.  2315000.  3150000.  2375000.
  1155000.  1615000.  1045000.    81000.  2675000.  2035000.  1480000.
   122000.   386000.   899999.  7650000.  2625000.   132000.  2065000.
  1399999.  2765000.   232000.   522000.  3380000.   389000.   834000.
   599000.  2129000.   116500.  3600000.   119000.  4900000.    88000.
  1795000.  3950000.   103000.   360009.  1099000.   679000.  9500000.
   288000.  5700000.   163000.  1855000.  3060000.  5500000.  3290000.
   397000.   418000.   588000. 17000000.   954955.  9800000.   324000.
   839000.  3135000.  2825000.   248000.  2530000.  2323000.  3175000.
  4250000.  1415000.  9200000.  1699000.  2975000.  3300000.  1535000.
  4850000.   127500.  1789999.  1435000.    74000.  3400000.  4300000.
   156000.  2980000.   149500.  8400000.  3040000.   298000.  1118000.
   597000.  6300000.   371000.  5400000.   517000.  2190000.  2799000.
   158000.  4350000.  1515000.  2210000.   162000.  1485000.  1234560.
  2030000.  2390000.   173000.   511000. 15000000.   236000.   853000.
  4980000.  1999000. 13500000.  7300000.   796000.  1234000.  1690000.
   107000.  2178000.   487000.   799999.  1043000.]
======================
Unique values of Registered City
['Karachi' 'Hyderabad' 'Bagh' 'Sukkar' 'Bahawalnagar' 'Lahore' 'Askoley'
 'Khanpur' 'Quetta' 'Karak' 'Islamabad' 'Sialkot' 'Pakpattan' 'Lasbela'
 'Sukkur' 'Rawalpindi' 'Bahawalpur' 'Ali Masjid' 'Multan' 'Khaplu' 'Tank'
 'Badin' 'Rahimyar Khan' 'Chilas' 'Kasur' 'Khushab' 'Vehari' 'Chitral'
 'Khanewal' 'Attock' 'Larkana' 'Bela' 'Khairpur']
======================
Unique values of Transaction Type
['Cash' 'Installment/Leasing']
======================
Unique values of Year
[1997. 2006. 1998. 2010. 2013. 2012. 2017. 2009. 1994. 1984. 2005. 1988.
 1995. 1990. 2014. 1989. 2001. 2000. 2007. 2002. 2015. 1999. 1991. 1982.
 2004. 2003. 2011. 1987. 1993. 2016. 1986. 2008. 2018. 1981. 1978. 1996.
 1985. 1992. 1980. 1983. 1973. 1964. 1969. 1952. 1979. 1974. 1976. 1962.
 1967. 1970. 1972. 1960. 1951. 1963. 1977. 1971. 1975. 1925. 1968.]
======================

In [26]:
cars_data['Brand'].replace(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',
       'Other', 'Nissan', 'BMW', 'Mazda', 'Chevrolet', 'Daewoo',
       'Hyundai', 'FAW', 'Mercedes', 'Classic', 'Lexus', 'Audi', 'Range',
       'Changan', 'Porsche'],
                          [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
                          ,inplace=True)

C:\Users\FUJITSU\AppData\Local\Temp\ipykernel_15140\2758656943.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['Brand'].replace(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',
C:\Users\FUJITSU\AppData\Local\Temp\ipykernel_15140\2758656943.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['Brand'].replace(['Toyota', 'Suzuki', 'Honda', 'Daihatsu', 'Mitsubishi', 'KIA',

In [27]:
cars_data['Condition'].unique()

array(['Used', 'New'], dtype=object)

In [31]:
cars_data['Condition'] = cars_data['Condition'].replace(['Used', 'New'], [1, 2])

In [29]:
cars_data['Fuel'].unique()

array(['Diesel', 'Petrol', 'CNG', 'Hybrid', 'LPG'], dtype=object)

In [32]:
 cars_data['Fuel'] = cars_data['Fuel'].replace(['Diesel', 'Petrol', 'CNG', 'Hybrid', 'LPG'], [1, 2, 3, 4, 5])

In [33]:
cars_data['Model'].unique()

array(['Prado', 'Bolan', 'Alto', 'Corolla XLI', 'Corrolla Altis',
       'Cultus VXL', 'Civic VTi', 'Khyber', 'Liana', 'Passo',
       'Civic Prosmetic', 'Civic EXi', 'Charade', 'Pajero Mini',
       'Margalla', 'City IVTEC', 'Classic', 'Other', 'Corolla GLI',
       'Cultus VXR', 'Dayz Highway Star', 'Mehran VX', 'Vitz',
       'Mehran VXR', 'Carry', 'Cultus VX', 'Baleno', 'Mira',
       'Civic VTi Oriel Prosmatec', 'Cuore', 'Corolla 2.0 D',
       'Corolla XE', 'Surf', 'FX', 'City IDSI', 'Premio', 'Sprinter',
       '3 Series', 'Hilux', 'Lancer', 'Swift', 'Estima', 'Vamos',
       'Starlet', 'Prius', 'Joy', '323', 'Racer', 'Sunny', 'Accord',
       'Zest', 'AD Van', 'APV', 'March', 'Pride', 'Sportage',
       'Terios Kid', 'Santro', 'Fit', 'V2', 'City Aspire',
       'Civic VTi Oriel', 'BR-V', 'Kei', 'Probox', 'Hijet', '86', 'Yaris',
       'Aygo', 'Rush', 'Dayz', 'Fortuner', 'Every', 'Camry', 'Aqua',
       'Corolla Assista', 'Sera', 'Acty', 'Moco', 'Wagon R', 'Smart',
       'Demio', 'Corona', 'Every Wagon', 'Civic Hybrid', 'Duet', 'Vezel',
       'Corolla Axio', 'City Vario', 'Corolla Fielder', 'Palette Sw',
       'Platz', 'Lancer Evolution', 'Move', 'Gx Series', '5 Series',
       '240 Gd', 'Mira Cocoa', 'Wingroad', 'Belta', 'Atrai Wagon',
       'Minicab Bravo', 'Allion', 'Blue Bird', 'Exclusive', 'N Wgn',
       'CT200h', 'Spectra', 'Beat', 'Mark II', 'Airwave', 'Supra',
       'Ek Wagon', 'EK Custom', 'Lite Ace', '120 Y', 'Harrier',
       'Pixis Epoch', '626', 'Galant', 'Sonica', 'Carol Eco', 'Accent',
       'IST', 'Land Cruiser', 'Palette', 'Juke', 'Potohar', 'CR-V',
       'Clipper', 'Sirius', 'Roox', '350Z', 'Pajero', 'Vitara',
       'Alto Lapin', 'Wagon R Stingray', 'Prius Alpha', 'Minica', 'Cast',
       'Carol', 'Hustler', 'S Class', 'Boon', 'Jimny', 'Fj Cruiser',
       'X-PV', 'Esse', 'Mirage', 'RX8', 'Carisma', 'iQ', 'Ek Sport',
       'CLK Class', 'Note', 'Stream', 'Carrier', 'Town Ace', 'I', 'N Box',
       'Excel', 'B2200', 'Tundra', 'Scrum', 'Celica', 'Van', 'C Class',
       'Pickup', 'Kizashi', 'Freed', 'RX Series', 'Life', 'Otti',
       'Spacia', 'Cervo', 'X5 Series', '200 D', 'Patrol', 'Acura',
       'Crown', 'Copen', 'Scrum Wagon', 'Charmant', 'Mark X', 'Spike',
       'Vogue', 'Axela', '929', 'Ravi', 'Noah', 'Jade Hybrid', 'Tanto',
       'X Trail', 'EK Space Custom', 'Cielo', 'I Mivec', 'N One', 'i8',
       'S660', 'Tiida', 'CR-Z', 'Verossa', 'Flair Wagon', 'Grace Hybrid',
       'E Class', 'Wish', 'L300', 'Auris', 'Cayenne', 'Silverado',
       'Insight', 'Thats', 'C-HR', 'Familia Van', 'Jimny Sierra',
       'D Series', 'Escudo', 'Vanette', 'Rvr', 'LX Series', '250 D',
       'Cami', 'Bluebird Sylphy', 'Pino', 'Ignis', 'A4', 'Wake', 'Spark',
       'Sirion', 'Q7', 'Zest Spark', 'Cruze', 'Avanza', 'Flair', 'ISIS',
       'Cross Road', '7 Series', 'Matiz', 'Pulsar', 'Ciaz', 'A6',
       'Sonata', '6 Series', 'Cressida', 'Solio', 'Alphard Hybrid',
       'Azwagon', 'Rav4', 'Toyo Ace'], dtype=object)

In [35]:
cars_data['Model'] = cars_data['Model'].replace(
        ['Prado', 'Bolan', 'Alto', 'Corolla XLI', 'Corrolla Altis', 'Cultus VXL', 'Civic VTi', 'Khyber', 'Liana', 'Passo',
        'Civic Prosmetic', 'Civic EXi', 'Charade', 'Pajero Mini', 'Margalla', 'City IVTEC', 'Classic', 'Other', 'Corolla GLI',
        'Cultus VXR', 'Dayz Highway Star', 'Mehran VX', 'Vitz', 'Mehran VXR', 'Carry', 'Cultus VX', 'Baleno', 'Mira',
        'Civic VTi Oriel Prosmatec', 'Cuore', 'Corolla 2.0 D', 'Corolla XE', 'Surf', 'FX', 'City IDSI', 'Premio', 'Sprinter',
        '3 Series', 'Hilux', 'Lancer', 'Swift', 'Estima', 'Vamos', 'Starlet', 'Prius', 'Joy', '323', 'Racer', 'Sunny', 'Accord',
        'Zest', 'AD Van', 'APV', 'March', 'Pride', 'Sportage', 'Terios Kid', 'Santro', 'Fit', 'V2', 'City Aspire',
        'Civic VTi Oriel', 'BR-V', 'Kei', 'Probox', 'Hijet', '86', 'Yaris', 'Aygo', 'Rush', 'Dayz', 'Fortuner', 'Every', 'Camry', 'Aqua',
        'Corolla Assista', 'Sera', 'Acty', 'Moco', 'Wagon R', 'Smart', 'Demio', 'Corona', 'Every Wagon', 'Civic Hybrid', 'Duet', 'Vezel',
        'Corolla Axio', 'City Vario', 'Corolla Fielder', 'Palette Sw', 'Platz', 'Lancer Evolution', 'Move', 'Gx Series', '5 Series',
        '240 Gd', 'Mira Cocoa', 'Wingroad', 'Belta', 'Atrai Wagon', 'Minicab Bravo', 'Allion', 'Blue Bird', 'Exclusive', 'N Wgn',
        'CT200h', 'Spectra', 'Beat', 'Mark II', 'Airwave', 'Supra', 'Ek Wagon', 'EK Custom', 'Lite Ace', '120 Y', 'Harrier',
        'Pixis Epoch', '626', 'Galant', 'Sonica', 'Carol Eco', 'Accent', 'IST', 'Land Cruiser', 'Palette', 'Juke', 'Potohar', 'CR-V',
        'Clipper', 'Sirius', 'Roox', '350Z', 'Pajero', 'Vitara', 'Alto Lapin', 'Wagon R Stingray', 'Prius Alpha', 'Minica', 'Cast',
        'Carol', 'Hustler', 'S Class', 'Boon', 'Jimny', 'Fj Cruiser', 'X-PV', 'Esse', 'Mirage', 'RX8', 'Carisma', 'iQ', 'Ek Sport',
        'CLK Class', 'Note', 'Stream', 'Carrier', 'Town Ace', 'I', 'N Box', 'Excel', 'B2200', 'Tundra', 'Scrum', 'Celica', 'Van', 'C Class',
        'Pickup', 'Kizashi', 'Freed', 'RX Series', 'Life', 'Otti', 'Spacia', 'Cervo', 'X5 Series', '200 D', 'Patrol', 'Acura',
        'Crown', 'Copen', 'Scrum Wagon', 'Charmant', 'Mark X', 'Spike', 'Vogue', 'Axela', '929', 'Ravi', 'Noah', 'Jade Hybrid', 'Tanto',
        'X Trail', 'EK Space Custom', 'Cielo', 'I Mivec', 'N One', 'i8', 'S660', 'Tiida', 'CR-Z', 'Verossa', 'Flair Wagon', 'Grace Hybrid',
        'E Class', 'Wish', 'L300', 'Auris', 'Cayenne', 'Silverado', 'Insight', 'Thats', 'C-HR', 'Familia Van', 'Jimny Sierra',
        'D Series', 'Escudo', 'Vanette', 'Rvr', 'LX Series', '250 D', 'Cami', 'Bluebird Sylphy', 'Pino', 'Ignis', 'A4', 'Wake', 'Spark',
        'Sirion', 'Q7', 'Zest Spark', 'Cruze', 'Avanza', 'Flair', 'ISIS', 'Cross Road', '7 Series', 'Matiz', 'Pulsar', 'Ciaz', 'A6',
        'Sonata', '6 Series', 'Cressida', 'Solio', 'Alphard Hybrid', 'Azwagon', 'Rav4', 'Toyo Ace'],
        [i for i in range(1, 250)]
    ).infer_objects(copy=False)

In [36]:
cars_data['Registered City'].unique()

array(['Karachi', 'Hyderabad', 'Bagh', 'Sukkar', 'Bahawalnagar', 'Lahore',
       'Askoley', 'Khanpur', 'Quetta', 'Karak', 'Islamabad', 'Sialkot',
       'Pakpattan', 'Lasbela', 'Sukkur', 'Rawalpindi', 'Bahawalpur',
       'Ali Masjid', 'Multan', 'Khaplu', 'Tank', 'Badin', 'Rahimyar Khan',
       'Chilas', 'Kasur', 'Khushab', 'Vehari', 'Chitral', 'Khanewal',
       'Attock', 'Larkana', 'Bela', 'Khairpur'], dtype=object)

In [38]:
cars_data['Registered City'] = cars_data['Registered City'].replace(
    ['Karachi', 'Hyderabad', 'Bagh', 'Sukkar', 'Bahawalnagar', 'Lahore',
     'Askoley', 'Khanpur', 'Quetta', 'Karak', 'Islamabad', 'Sialkot',
     'Pakpattan', 'Lasbela', 'Sukkur', 'Rawalpindi', 'Bahawalpur',
     'Ali Masjid', 'Multan', 'Khaplu', 'Tank', 'Badin', 'Rahimyar Khan',
     'Chilas', 'Kasur', 'Khushab', 'Vehari', 'Chitral', 'Khanewal',
     'Attock', 'Larkana', 'Bela', 'Khairpur'],
    list(range(1, 34))
).infer_objects(copy=False)

In [39]:
cars_data['Transaction Type'].unique()

array(['Cash', 'Installment/Leasing'], dtype=object)

In [41]:
cars_data['Transaction Type'] = cars_data['Transaction Type'].replace(
    ['Cash', 'Installment/Leasing'],
    [1, 2]
).infer_objects(copy=False)

In [42]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8408 entries, 0 to 10576
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             8408 non-null   int64
 1   Condition         8408 non-null   int64
 2   Fuel              8408 non-null   int64
 3   KMs Driven        8408 non-null   float64
 4   Model             8408 non-null   int64
 5   Price             8408 non-null   float64
 6   Registered City   8408 non-null   int64
 7   Transaction Type  8408 non-null   int64
 8   Year              8408 non-null   float64
dtypes: float64(3), int64(6)
memory usage: 656.9 KB

In [43]:
cars_data.reset_index(inplace=True)

In [44]:
cars_data.drop(columns=['index'], inplace=True)

In [45]:
cars_data

,Brand,Condition,Fuel,KMs Driven,Model,Price,Registered City,Transaction Type,Year
0,1,1,1,1.0,1,2100000.0,1,1,1997.0
1,2,1,2,100000.0,2,380000.0,1,1,2006.0
2,2,1,3,12345.0,2,340000.0,1,1,1998.0
3,2,1,2,94000.0,3,535000.0,1,1,2010.0
4,1,1,2,100000.0,4,1430000.0,1,1,2013.0
...,...,...,...,...,...,...,...,...,...
8403,2,1,2,10000.0,20,495000.0,1,1,2004.0
8404,2,1,2,30000.0,15,385000.0,1,1,1996.0
8405,2,1,3,90000.0,20,660000.0,1,1,2010.0
8406,2,1,2,25000.0,6,750000.0,1,1,2012.0
8407,3,1,3,123456.0,12,230000.0,1,1,1989.0

In [46]:
for col in cars_data.columns:
    print('------------')
    print(col)
    print(cars_data[col].unique())

------------
Brand
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
------------
Condition
[1 2]
------------
Fuel
[1 2 3 4 5]
------------
KMs Driven
[1.00000e+00 1.00000e+05 1.23450e+04 ... 1.00008e+05 5.63000e+04
 3.68525e+05]
------------
Model
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249]
------------
Price
[ 2100000.   380000.   340000.   535000.  1430000.  1620000.   450000.
  2900000.   490000.   480000.   230000.   770000.   160000.   425000.
   180000.   520000.   400000.  1400000.   175000.   120000.   590000.
   685000.   465000.  1190000.   850000.   370000.  1175000.  1675000.
   195000.   165000.   420000.   150000.   130000.   415000.   185000.
  1040000.   360000.  1150000.   265000.   435000.  1220000.   780000.
   250000.   875000.  1260000.   840000.   350000.  1050000.   730000.
  1070000.   410000.   155000.   320000.  1080000.   290000.   570000.
  4150000.    90000.  1740000.   916000.   110000.   765000.  1890000.
   790000.   785000.   270000.   550000.   825000.  3850000.  1250000.
   135000.  4500000.   430000.  2880000.   975000.   440000.   305000.
  1140000.   680000.   335000.  3350000.   405000.   865000.  1090000.
   300000.   750000.   820000.   373000.  2500000.  5350000.   200000.
  1160000.  9000000.    55000.  1110000.  2830000.   740000.   560000.
   690000.  1095000.   145000.  1710000.   900000.  2175000.   105000.
   485000.  1350000.  1100000.   260000.   210000.   170000.  1320000.
  1000000.   220000.   950000.   930000.  1275000.   760000.   980000.
   855000.   600000.    68000.   500000.   700000.   580000.   225000.
  1625000.   118000.   168000.   650000.    95000.   585000.  1525000.
  1730000.  2000000.   545000.   830000.   190000.   293000.   510000.
   310000.   365000.   540000.   330000.  1450000.   995000.   315000.
  1750000.  1079000.   530000.   245000.   910000.   280000.  1975000.
   860000.  1600000.   725000.   240000.   140000.   965000.  2325000.
  1120000.   960000.    60000.   795000.  1135000.   800000.   695000.
  1650000.  1550000.  1165000.  7550000.   215000.  1060000.  1200000.
  1125000.  1810000.  1900000.  1225000.  1375000.  2835000.   575000.
  1660000.   660000.   775000.   810000.   920000.   625000.  1850000.
   565000.  1170000.  1315000.   235000.   534999.   285000.  1865000.
  1425000.   880000.  1830000.  1490000.  1575000.   635000.  1025000.
   812000.   199000.   845000.  1185000.  1560000.   255000.   665000.
  1800000.  1396000.  1215000.   985000.   555000.   100000.   696000.
   935000.  1195000.   885000.   460000.   745000.   945000.   375000.
  2750000.  3200000.   835000.   413000.   675000.  1469000.  1775000.
   525000.  1300000.   505000.   470000.  2250000.  1370000.   355000.
  1285000.  1500000.   475000.   670000.  1995000.  1390000.   818000.
  1820000.  2650000.   710000.    85000.  2725000.  1020000.  1465000.
  1210000.  4600000.   395000.  2050000.   876000.   538000.  5000000.
  3090000.  2310000.   610000.  4000000.  1760000.  1340000.  1280000.
   848000.  1149000.   990000.   125000.   295000.  1325000.   284999.
   541000.   615000.  2350000.   620000.   521000.   669000.    80000.
   205000.  1035000.  1265000.  1075000.  1720000.   515000.   572500.
   385000.    75000.  2075000.  1178000.  1745000.   390000.  1875000.
  2700000.  1630000.  2800000.  2150000.   970000.  1055000.  2400000.
  1065000.   735000.   548000.   925000.   819000.   915000.   955000.
   495000.   595000.   630000.   499999.  1915000.  1965000.   870000.
   655000.   815000.  1245000.  2225000.  2385000.  1475000.  3900000.
  1725000.  1950000.  2290000.   890000.  1230000.  1275786.  2200000.
  1010000.  1835000.  1655000.  3050000.   275000.  3000000.   238000.
   720000.   361099.  5450000.   115000.    50000.  1585000.  3750000.
   137500.  1695000.  1030000.    70000.  3700000.   189000.  1149999.
  1255000.  1314000.   213500.  1180000.   382000.  1299987.  1580000.
  3295000.  2230000.  1700000.  4400000.   445000.   700001.    65000.
   645000.   399000.   347000.  2140000.   112000. 27000000.  1145000.
  9100000.   640000.  3925000.   755000.   455000.  2690000.  2300000.
  6420000.  2600000.  1520000.  1360000.   943000.   715000.  1590000.
   444000.  1005000.  1395000.  1920000.  1785000.   159000.   699000.
  2665000.  6000000.   789000. 10000000.   325000.   324999.   258000.
   133000.  2180000.   605000.  1860000.  2090000.  1290000.   805000.
   268000.  1410000.   429000.  2285000.  2445000.   895000.  1270000.
  4100000.  1825000.  4975000.  2270000.  1115000.  2780000.   598000.
  2450000.  1295000.  3125000.   276000.  1385000.  1910000.  1790000.
  1940000.  2335000.  1130000.  2875000.  1085000.  2865000.  2060000.
  1015000.   402000.  1705000.   148000.  1670000.  2380000.  5800000.
  1440000.  1460000.  1545000.  2080000.   741000.  1240000.   272000.
   589000.   389999.  1985000.   359000.  2425000.  1925000.  1204000.
  1715000.  1665000.    99000.   492000.   222000.  6800000.   299000.
  2125000.  7500000.   642000.  2085000.  1345000.  1470000.   452000.
  1599000.  1680000.  2275000.  2979000.  1885000.  1770000.  1420000.
  2020000.  1310000.  1780000.  2565000.  2287650.  2195000.  2228650.
   999999.   567000.   998000.  1945000.  1990000.  1635000.  6500000.
   425200.   345000.  2340000.  2480000.   749000.  1570000.  1815000.
  2550000.  1565000.   331000.   187000.  6350000.  1870000.  2950000.
   940000.  4650000.  1235000.  6450000.  1930000.  1199000.  5100000.
  3095000.  3800000.  2015000.   489000.   412000.  1685000.   231000.
   858000. 12500000.  1330000.  6400000.  2925000.    62000.   993000.
   391000.   869000.  1840000.   299999.  2025000.  1335000.  2850000.
  1595000.    85500.  1540000.  8650000.   338000.   379000.  3070000.
  3170000.   718000.   949000.  2745000.  1994000.   398000.   989500.
  3225000.  4550000.  2490000.   348000.  3500000.  4800000.  2320000.
   497000.  1530000.    98000.  1099999.   799000.   323000.  1380000.
   705000.   899000.   243000.   269000.  2315000.  3150000.  2375000.
  1155000.  1615000.  1045000.    81000.  2675000.  2035000.  1480000.
   122000.   386000.   899999.  7650000.  2625000.   132000.  2065000.
  1399999.  2765000.   232000.   522000.  3380000.   389000.   834000.
   599000.  2129000.   116500.  3600000.   119000.  4900000.    88000.
  1795000.  3950000.   103000.   360009.  1099000.   679000.  9500000.
   288000.  5700000.   163000.  1855000.  3060000.  5500000.  3290000.
   397000.   418000.   588000. 17000000.   954955.  9800000.   324000.
   839000.  3135000.  2825000.   248000.  2530000.  2323000.  3175000.
  4250000.  1415000.  9200000.  1699000.  2975000.  3300000.  1535000.
  4850000.   127500.  1789999.  1435000.    74000.  3400000.  4300000.
   156000.  2980000.   149500.  8400000.  3040000.   298000.  1118000.
   597000.  6300000.   371000.  5400000.   517000.  2190000.  2799000.
   158000.  4350000.  1515000.  2210000.   162000.  1485000.  1234560.
  2030000.  2390000.   173000.   511000. 15000000.   236000.   853000.
  4980000.  1999000. 13500000.  7300000.   796000.  1234000.  1690000.
   107000.  2178000.   487000.   799999.  1043000.]
------------
Registered City
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]
------------
Transaction Type
[1 2]
------------
Year
[1997. 2006. 1998. 2010. 2013. 2012. 2017. 2009. 1994. 1984. 2005. 1988.
 1995. 1990. 2014. 1989. 2001. 2000. 2007. 2002. 2015. 1999. 1991. 1982.
 2004. 2003. 2011. 1987. 1993. 2016. 1986. 2008. 2018. 1981. 1978. 1996.
 1985. 1992. 1980. 1983. 1973. 1964. 1969. 1952. 1979. 1974. 1976. 1962.
 1967. 1970. 1972. 1960. 1951. 1963. 1977. 1971. 1975. 1925. 1968.]

In [47]:
cars_data.isnull().sum()

Brand               0
Condition           0
Fuel                0
KMs Driven          0
Model               0
Price               0
Registered City     0
Transaction Type    0
Year                0
dtype: int64

In [48]:
input_data = cars_data.drop(columns=['Price'])
output_data =cars_data['Price']

In [49]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2)

In [50]:
model = LinearRegression()

In [51]:
model.fit(x_train, y_train)

LinearRegression()

In [52]:
predict = model.predict(x_test)

In [53]:
predict

array([ 718831.92519302,  565070.83635559,  -27460.64158438, ...,
       1367433.21566212,  579643.2484007 , 1078648.28219059])

In [54]:
x_train.head(1)

,Brand,Condition,Fuel,KMs Driven,Model,Registered City,Transaction Type,Year
2180,2,1,2,12.0,3,1,1,2004.0

In [60]:
input_data_model = pd.DataFrame(
    [[4,2,2,100000,56,6,1,2021.0]],
    columns=['Brand','Condition','Fuel','KMs Driven','Model','Registered City','Transaction Type','Year'])

In [61]:
input_data_model

,Brand,Condition,Fuel,KMs Driven,Model,Registered City,Transaction Type,Year
0,4,2,2,100000,56,6,1,2021.0

In [62]:
model.predict(input_data_model)

array([1786112.07473862])

In [65]:
import pickle as pk

In [66]:
pk.dump(model,open('model.pkl','wb'))